# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5160b2b1d6061c85bf7c03d9a8a3167b5057dd0c24ce682057ee770eb7068732990ee8f9493bb3bb4adc7874ac2001627788bc913b31ff165a96123cc1faf89f

test:
  secret_key_base: e03dca1da9ca3d6fe16b504418d98080b58d5223e854b95d2e8c97c41a73bb71af625abdb3e18668913d5debcae4ff1cc63385966e45b1504aac7ab96034fbac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
